### ISSUE TITLE
一个漏洞

### ISSUE THREAD

**Issue by Norox0511** [MineCommanderCN/squid#1]
系统：Ubuntu 20.04 LTS
我在使用VSCode运行squid时出现如下错误
![2020-06-07 16-05-11 的屏幕截图](https://user-images.githubusercontent.com/52060599/83963963-28dc0200-a8dc-11ea-9e09-71c2a7da096d.png)

**Comment by MineCommanderCN** [comment]
开发环境为Visual Code 2019 @ Windows 10 1909 x64
你可以试试换个系统/IDE或者看看最新commit

**Comment by MineCommanderCN** [comment]
将_Nocreate替换成nocreate即可解决问题

**Comment by Norox0511** [comment]
还有问题，Linux不能使用windows.h
